"""Google TTS voice definitions for audio modality."""

from celeste.core import Provider

from ...languages import Language
from ...voices import Voice

# Source: https://ai.google.dev/gemini-api/docs/speech-generation#supported-languages
GOOGLE_SUPPORTED_LANGUAGES = [
    Language.ARABIC,
    Language.FILIPINO,
    Language.BANGLA,
    Language.FINNISH,
    Language.DUTCH,
    Language.GALICIAN,
    Language.ENGLISH,
    Language.GEORGIAN,
    Language.FRENCH,
    Language.GREEK,
    Language.GERMAN,
    Language.GUJARATI,
    Language.HINDI,
    Language.HAITIAN_CREOLE,
    Language.INDONESIAN,
    Language.HEBREW,
    Language.ITALIAN,
    Language.HUNGARIAN,
    Language.JAPANESE,
    Language.ICELANDIC,
    Language.KOREAN,
    Language.JAVANESE,
    Language.MARATHI,
    Language.KANNADA,
    Language.POLISH,
    Language.KONKANI,
    Language.PORTUGUESE,
    Language.LAO,
    Language.ROMANIAN,
    Language.LATIN,
    Language.RUSSIAN,
    Language.LATVIAN,
    Language.SPANISH,
    Language.LITHUANIAN,
    Language.TAMIL,
    Language.LUXEMBOURGISH,
    Language.TELUGU,
    Language.MACEDONIAN,
    Language.THAI,
    Language.MAITHILI,
    Language.TURKISH,
    Language.MALAGASY,
    Language.UKRAINIAN,
    Language.MALAY,
    Language.VIETNAMESE,
    Language.MALAYALAM,
    Language.AFRIKAANS,
    Language.MONGOLIAN,
    Language.ALBANIAN,
    Language.NEPALI,
    Language.AMHARIC,
    Language.NORWEGIAN_BOKMAL,
    Language.ARMENIAN,
    Language.NORWEGIAN_NYNORSK,
    Language.AZERBAIJANI,
    Language.ODIA,
    Language.BASQUE,
    Language.PASHTO,
    Language.BELARUSIAN,
    Language.PERSIAN,
    Language.BULGARIAN,
    Language.PUNJABI,
    Language.BURMESE,
    Language.SERBIAN,
    Language.CATALAN,
    Language.SINDHI,
    Language.CEBUANO,
    Language.SINHALA,
    Language.CHINESE_MANDARIN,
    Language.SLOVAK,
    Language.CROATIAN,
    Language.SLOVENIAN,
    Language.CZECH,
    Language.SWAHILI,
    Language.DANISH,
    Language.SWEDISH,
    Language.ESTONIAN,
    Language.URDU,
]

# Snapshot 2026-07-14: 30 prebuilt voices.
# Source: https://ai.google.dev/gemini-api/docs/speech-generation#voices
GOOGLE_VOICES = [
    Voice(
        id=name,
        provider=Provider.GOOGLE,
        name=name,
        description=description,
        languages=set(GOOGLE_SUPPORTED_LANGUAGES),
    )
    for name, description in [
        ("Zephyr", "Bright"),
        ("Puck", "Upbeat"),
        ("Charon", "Informative"),
        ("Kore", "Firm"),
        ("Fenrir", "Excitable"),
        ("Leda", "Youthful"),
        ("Orus", "Firm"),
        ("Aoede", "Breezy"),
        ("Callirrhoe", "Easy-going"),
        ("Autonoe", "Bright"),
        ("Enceladus", "Breathy"),
        ("Iapetus", "Clear"),
        ("Umbriel", "Easy-going"),
        ("Algieba", "Smooth"),
        ("Despina", "Smooth"),
        ("Erinome", "Clear"),
        ("Algenib", "Gravelly"),
        ("Rasalgethi", "Informative"),
        ("Laomedeia", "Upbeat"),
        ("Achernar", "Soft"),
        ("Alnilam", "Firm"),
        ("Schedar", "Even"),
        ("Gacrux", "Mature"),
        ("Pulcherrima", "Forward"),
        ("Achird", "Friendly"),
        ("Zubenelgenubi", "Casual"),
        ("Vindemiatrix", "Gentle"),
        ("Sadachbia", "Lively"),
        ("Sadaltager", "Knowledgeable"),
        ("Sulafat", "Warm"),
    ]
]
