"""Language definitions for speech generation."""

from enum import StrEnum


class Language(StrEnum):
    """Language tags for speech generation.

    Values are BCP-47 language subtags, allowing both enum and string usage:
    - `Language.ENGLISH` → "en"
    - `"en"` → works directly
    """

    AFRIKAANS = "af"
    ALBANIAN = "sq"
    AMHARIC = "am"
    ARABIC = "ar"
    ARMENIAN = "hy"
    AZERBAIJANI = "az"
    BANGLA = "bn"
    BASQUE = "eu"
    BELARUSIAN = "be"
    BULGARIAN = "bg"
    BURMESE = "my"
    CATALAN = "ca"
    CEBUANO = "ceb"
    CHINESE = "zh"
    CHINESE_MANDARIN = "cmn"
    CROATIAN = "hr"
    CZECH = "cs"
    DANISH = "da"
    DUTCH = "nl"
    ENGLISH = "en"
    ESTONIAN = "et"
    FILIPINO = "fil"
    FINNISH = "fi"
    FRENCH = "fr"
    GALICIAN = "gl"
    GEORGIAN = "ka"
    GERMAN = "de"
    GREEK = "el"
    GUJARATI = "gu"
    HAITIAN_CREOLE = "ht"
    HEBREW = "he"
    HINDI = "hi"
    HUNGARIAN = "hu"
    ICELANDIC = "is"
    INDONESIAN = "id"
    ITALIAN = "it"
    JAPANESE = "ja"
    JAVANESE = "jv"
    KANNADA = "kn"
    KONKANI = "kok"
    KOREAN = "ko"
    LAO = "lo"
    LATIN = "la"
    LATVIAN = "lv"
    LITHUANIAN = "lt"
    LUXEMBOURGISH = "lb"
    MACEDONIAN = "mk"
    MAITHILI = "mai"
    MALAGASY = "mg"
    MALAY = "ms"
    MALAYALAM = "ml"
    MARATHI = "mr"
    MONGOLIAN = "mn"
    NEPALI = "ne"
    NORWEGIAN = "no"
    NORWEGIAN_BOKMAL = "nb"
    NORWEGIAN_NYNORSK = "nn"
    ODIA = "or"
    PASHTO = "ps"
    PERSIAN = "fa"
    POLISH = "pl"
    PORTUGUESE = "pt"
    PUNJABI = "pa"
    ROMANIAN = "ro"
    RUSSIAN = "ru"
    SERBIAN = "sr"
    SINDHI = "sd"
    SINHALA = "si"
    SLOVAK = "sk"
    SLOVENIAN = "sl"
    SPANISH = "es"
    SWAHILI = "sw"
    SWEDISH = "sv"
    TAMIL = "ta"
    TELUGU = "te"
    THAI = "th"
    TURKISH = "tr"
    UKRAINIAN = "uk"
    URDU = "ur"
    VIETNAMESE = "vi"


__all__ = ["Language"]
